// Hotel API

   ### Get hotels and rooms

GET {{url}}/hotels

###

   ### Get Hotel by id and its rooms

GET {{url}}/hotels/2

###

   ### Create hotel

POST {{url}}/hotels
Content-Type: application/json

{
  "hotelName": "Holiday Inn",
  "hotelAddress": "Stuttgart",
  "hotelType": "STANDARD"
}

###

   ### Updated hotel (choose hotel to updated by id)

PUT {{url}}/hotels/1
Content-Type: application/json

{
  "hotelName": "Ritz Carlton",
  "hotelAddress": "London City",
  "hotelType": "LUXURY"
}

###

   ### Delete hotel and its rooms

DELETE {{url}}/hotels/1

###

// Room API

   ### Get all rooms

GET {{url}}/rooms

###

    ### Geet room by roomíd
GET {{url}}/rooms/2

###

    ### Create room and at to hotel (number is hotelid)

POST {{url}}/rooms/hotel/1
Content-Type: application/json

{
  "roomNumber": 11,
  "roomPrice": 1150,
  "roomType": "SINGLE"
}
